name: POE-Exceptions
version: 0.0401
author: Matt Cashner (sungo@pobox.com)
license: bsd
distribution_type: module
requires:
  POE: 0
  Test::More: 0
  Carp: 0
no_index:
  directory:
    - inc
generated_by: Module::Install version 0.37
