#XXXXXXX This is a prototype!!!  It will change in the future!!! XXXXX#
name:         POE-Exceptions
version:      0.03
version_from: VERSION
installdirs:  site
requires:
    Carp:                          0
    POE:                           0.25
    Test::More:                    0

distribution_type: module
generated_by: ExtUtils::MakeMaker version 6.13
